### ISSUE TITLE
broken pkgdb messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#193]
We got this error email in staging today:

```
  File "/usr/lib64/python2.6/threading.py", line 504 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.6/threading.py", line 532 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/threadpool.py", line 210 in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59 in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37 in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.6/site-packages/moksha/hub/api/consumer.py", line 192 in _work
    self.log.exception(message)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/moksha/hub/api/consumer.py", line 190, in _work
    self.consume(message)
  File "/usr/lib/python2.6/site-packages/fedmsg/consumers/ircbot.py", line 321, in consume
    short=client.factory.short,
  File "/usr/lib/python2.6/site-packages/fedmsg/consumers/ircbot.py", line 271, in prettify
    link = fedmsg.meta.msg2link(msg, **self.hub.config)
  File "/usr/lib/python2.6/site-packages/fedmsg/meta/__init__.py", line 137, in __wrapper
    return f(msg, **config)
  File "/usr/lib/python2.6/site-packages/fedmsg/meta/__init__.py", line 156, in __wrapper
    return f(msg, processor=processor, **config)
  File "/usr/lib/python2.6/site-packages/fedmsg/meta/__init__.py", line 252, in msg2link
    return processor.link(msg, **config)
  File "/usr/lib/python2.6/site-packages/fedmsg_meta_fedora_infrastructure/pkgdb.py", line 533, in link
    package=msg['msg']['package_listing']['package']['name']
KeyError: 'package_listing'
```

Here's the message that triggered it:

```javascript
{
    "certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVWakNDQTcrZ0F3SUJBZ0lDQVQwd0RRWUpL\nb1pJaHZjTkFRRUZCUUF3Z2FBeEN6QUpCZ05WQkFZVEFsVlQKTVFzd0NRWURWUVFJRXdKT1F6RVFN\nQTRHQTFVRUJ4TUhVbUZzWldsbmFERVhNQlVHQTFVRUNoTU9SbVZrYjNKaApJRkJ5YjJwbFkzUXhE\nekFOQmdOVkJBc1RCbVpsWkcxelp6RVBNQTBHQTFVRUF4TUdabVZrYlhObk1ROHdEUVlEClZRUXBF\nd1ptWldSdGMyY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1UUdabFpHOXlZWEJ5YjJwbFkz\nUXUKYjNKbk1CNFhEVEUwTURReU16RTBNekF3TUZvWERUSTBNRFF5TURFME16QXdNRm93Z2VReEN6\nQUpCZ05WQkFZVApBbFZUTVFzd0NRWURWUVFJRXdKT1F6RVFNQTRHQTFVRUJ4TUhVbUZzWldsbmFE\nRVhNQlVHQTFVRUNoTU9SbVZrCmIzSmhJRkJ5YjJwbFkzUXhEekFOQmdOVkJBc1RCbVpsWkcxelp6\nRXhNQzhHQTFVRUF4TW9jR3RuWkdJdGNHdG4KWkdJd01TNXpkR2N1Y0doNE1pNW1aV1J2Y21Gd2Nt\nOXFaV04wTG05eVp6RXhNQzhHQTFVRUtSTW9jR3RuWkdJdApjR3RuWkdJd01TNXpkR2N1Y0doNE1p\nNW1aV1J2Y21Gd2NtOXFaV04wTG05eVp6RW1NQ1FHQ1NxR1NJYjNEUUVKCkFSWVhZV1J0YVc1QVpt\nVmtiM0poY0hKdmFtVmpkQzV2Y21jd2daOHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZMEEKTUlHSkFv\nR0JBTnkrTFduVTZ2eGc1MThmTFpvQkdKZXB2cmN5NkpHMVhHQmMwcGtJOTVLRkhJS0pNU0NTdm1G\nWgphVTl6ZjY0MWZqLytvYXRiZjJpbFlZbzVaejlnUEp2NEZ3S0I2STVsMEd5aGZBSmpKZ1cxanI1\nbUFiTXNwTVJCCmxVbVVveS9mRHAySVZoSStlVDNuRUxCTUxtNnFhTkFVMDNiZUJMMjVWeUw0c2tT\nRUdiRlRBZ01CQUFHamdnRlgKTUlJQlV6QUpCZ05WSFJNRUFqQUFNQzBHQ1dDR1NBR0crRUlCRFFR\nZ0ZoNUZZWE41TFZKVFFTQkhaVzVsY21GMApaV1FnUTJWeWRHbG1hV05oZEdVd0hRWURWUjBPQkJZ\nRUZOeHhBSkZvY0xZU2psY2JTTFBld285dElzMStNSUhWCkJnTlZIU01FZ2Mwd2djcUFGR3RBV3Zr\nU0NJbFo1MW5sQmZVQ0hRcE9meFFBb1lHbXBJR2pNSUdnTVFzd0NRWUQKVlFRR0V3SlZVekVMTUFr\nR0ExVUVDQk1DVGtNeEVEQU9CZ05WQkFjVEIxSmhiR1ZwWjJneEZ6QVZCZ05WQkFvVApEa1psWkc5\neVlTQlFjbTlxWldOME1ROHdEUVlEVlFRTEV3Wm1aV1J0YzJjeER6QU5CZ05WQkFNVEJtWmxaRzF6\nClp6RVBNQTBHQTFVRUtSTUdabVZrYlhObk1TWXdKQVlKS29aSWh2Y05BUWtCRmhkaFpHMXBia0Jt\nWldSdmNtRncKY205cVpXTjBMbTl5WjRJSkFPTlFIa2RQRng1Rk1CTUdBMVVkSlFRTU1Bb0dDQ3NH\nQVFVRkJ3TUNNQXNHQTFVZApEd1FFQXdJSGdEQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQWRXN1Jm\ndTYxeURlbVJTYVZ0eWZNbGtoZ1VKNmpOCk5WSjVBVU1YN2RMVjFPTzJlTFNpZnZhVU1nMmY0SEdR\nMnZONC8zNUEwM1ZMcUJ4am9rLzFhVW5kOUN3V2thbDEKNmZKQktITlJpMlBJcG1nZFp4eldCQ1Bx\nSTBJbHdVUEpuR01KdWlNMFcvMm9FZHUxbVVFdEM0NTV6TW1qYjVwdgpLbGFWQ05Pa0REVHBkZz09\nCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\n", 
    "i": 1, 
    "msg": {
        "agent": "vondruch", 
        "collection": {
            "branchname": "master", 
            "dist_tag": ".fc22", 
            "koji_name": "rawhide", 
            "name": "Fedora", 
            "status": "Under Development", 
            "version": "devel"
        }, 
        "info": {
            "pkg_collection": "master", 
            "pkg_critpath": false, 
            "pkg_description": "Retrieve the binding of a method's caller. Can also retrieve bindings even further up the stack.", 
            "pkg_name": "rubygem-binding_of_caller", 
            "pkg_poc": "vondruch", 
            "pkg_review_url": "bla", 
            "pkg_status": "Approved", 
            "pkg_summary": "Retrieve the binding of a method's caller", 
            "pkg_upstream_url": ""
        }, 
        "package": null
    }, 
    "msg_id": "2015-d44d3455-bf90-4b8d-ae59-fe5750054f9c", 
    "signature": "ShOFKIm0bYTyXUUIPeJXjwCUZMxXp4Cafie23CpTUtLlR4tFjcipTJKO8vcIlUqnXzF7cQI1C2mB\nzx5SHhv0r94KdZcPYL3LTYxeYuKZbsBuqZR8cLMYgO28CgeuirFCt3X+Xmhw3dEyg7kWNCVuJGiO\nS9QRLZjPnkfCqWZzbgs=\n", 
    "source_name": "datanommer", 
    "source_version": "0.6.4", 
    "timestamp": 1422292483.0, 
    "topic": "org.fedoraproject.stg.pkgdb.package.new.request"
}
```

/cc @pypingou what's going on here?

**Comment by pypingou** [comment]
So this is a request for a new package to be added to pkgdb which indeed cannot satisfy: ``package=msg['msg']['package_listing']['package']['name']``

The package name can be found in ``msg['info']['pkg_name']``

**Comment by ralphbean** [comment]
I grepped for ``new.request`` in the fedmsg_meta code and it's not in there anywhere.  We'll need to add tests for this new message and any others that come in the latest pkgdb release in order for them to show up on fedmsg.com, too.

**Comment by ralphbean** [comment]
> I grepped for new.request in the fedmsg_meta code and it's not in there anywhere

Not true!  I typoed.  There it is.
