### ISSUE TITLE
Traceback in fedimg processor

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#268]
[This message](https://apps.fedoraproject.org/datagrepper/id?id=2015-4ecd6855-edb8-4de1-999c-3219e24aef84&size=extra-large) causes fedmsg_meta to traceback, like this:

```python
  File "/usr/lib64/python2.6/threading.py", line 504 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.6/threading.py", line 532 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/threadpool.py", line 210 in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59 in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37 in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.6/site-packages/moksha/hub/api/consumer.py", line 192 in _work
    self.log.exception(message)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/moksha/hub/api/consumer.py", line 190, in _work
    self.consume(message)
  File "/usr/lib/python2.6/site-packages/fedmsg/consumers/ircbot.py", line 319, in consume
    short=client.factory.short,
  File "/usr/lib/python2.6/site-packages/fedmsg/consumers/ircbot.py", line 270, in prettify
    subtitle = fedmsg.meta.msg2subtitle(msg, **self.hub.config)
  File "/usr/lib/python2.6/site-packages/fedmsg/meta/__init__.py", line 133, in __wrapper
    return f(msg, **config)
  File "/usr/lib/python2.6/site-packages/fedmsg/meta/__init__.py", line 152, in __wrapper
    return f(msg, processor=processor, **config)
  File "/usr/lib/python2.6/site-packages/fedmsg/meta/__init__.py", line 222, in msg2subtitle
    return processor.subtitle(msg, **config)
  File "/usr/lib/python2.6/site-packages/fedmsg_meta_fedora_infrastructure/fedimg.py", line 52, in subtitle
    ami = msg['msg']['extra']['id']
TypeError: 'NoneType' object is unsubscriptable
```

@oddshocks, this is in the latest fedimg code you were working on in #260.  Can you have a look?

**Comment by ralphbean** [comment]
Since this is causing datagrepper to traceback too, it's kind of hard to get the original message.

Here it is:

```javascript
{
    "i": 3, 
    "msg": {
        "destination": "EC2 (ap-northeast-1)", 
        "extra": null, 
        "image_name": "Fedora-Cloud-Base-22-20150512.x86_64", 
        "image_url": "Fedora-Cloud-Base-22-20150512.x86_64", 
        "status": "started"
    }, 
    "msg_id": "2015-4ecd6855-edb8-4de1-999c-3219e24aef84", 
    "source_name": "datanommer", 
    "source_version": "0.6.5", 
    "timestamp": 1431464408.0, 
    "topic": "org.fedoraproject.prod.fedimg.image.test"
}
```

**Comment by oddshocks** [comment]
I think https://github.com/fedora-infra/fedimg/pull/27 should be the fix we're looking for. Just an oversight.
