### ISSUE TITLE
Keyerror on some pagure messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#275]
Here's the traceback:

```python
  File "/usr/lib64/python2.7/threading.py", line 784 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 167 in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118 in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81 in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 186 in _work
    self.log.exception(message)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 184, in _work
    self.consume(message)
  File "/usr/lib/python2.7/site-packages/fedmsg/consumers/ircbot.py", line 319, in consume
    short=client.factory.short,
  File "/usr/lib/python2.7/site-packages/fedmsg/consumers/ircbot.py", line 270, in prettify
    subtitle = fedmsg.meta.msg2subtitle(msg, **self.hub.config)
  File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 133, in __wrapper
    return f(msg, **config)
  File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 152, in __wrapper
    return f(msg, processor=processor, **config)
  File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 222, in msg2subtitle
    return processor.subtitle(msg, **config)
  File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/pagure.py", line 84, in subtitle
    user = msg['msg']['agent']
KeyError: 'agent'
```

and it was caused by this message:

```python
>>> import requests
>>> response = requests.get('https://apps.fedoraproject.org/datagrepper/id?id=2015-c6561fe2-3815-469c-a288-8f36cf8fdda3')
>>> import pprint; pprint.pprint(response.json())
{u'certificate': u'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVTRENDQTdHZ0F3SUJBZ0lDQWZzd0RRWUpL\nb1pJaHZjTkFRRUZCUUF3Z2FBeEN6QUpCZ05WQkFZVEFsVlQKTVFzd0NRWURWUVFJRXdKT1F6RVFN\nQTRHQTFVRUJ4TUh
VbUZzWldsbmFERVhNQlVHQTFVRUNoTU9SbVZrYjNKaApJRkJ5YjJwbFkzUXhE\nekFOQmdOVkJBc1RCbVpsWkcxelp6RVBNQTBHQTFVRUF4TUdabVZrYlhObk1ROHdEUVlEClZRUXBF\nd1ptWldSdGMyY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV
2x1UUdabFpHOXlZWEJ5YjJwbFkz\nUXUKYjNKbk1CNFhEVEUxTURVeE9ERTNNamMxTTFvWERUSTFNRFV4TlRFM01qYzFNMW93Z2RZeEN6\nQUpCZ05WQkFZVApBbFZUTVFzd0NRWURWUVFJRXdKT1F6RVFNQTRHQTFVRUJ4TUhVbUZzWldsbmFE\nRVhNQ
lVHQTFVRUNoTU9SbVZrCmIzSmhJRkJ5YjJwbFkzUXhEekFOQmdOVkJBc1RCbVpsWkcxelp6\nRXFNQ2dHQTFVRUF4TWhjR0ZuZFhKbExYQmgKWjNWeVpUQXhMbVpsWkc5eVlYQnliMnBsWTNRdWIz\nSm5NU293S0FZRFZRUXBFeUZ3WVdkMWNtVXRjR0Z
uZFhKbApNREV1Wm1Wa2IzSmhjSEp2YW1WamRD\nNXZjbWN4SmpBa0Jna3Foa2lHOXcwQkNRRVdGMkZrYldsdVFHWmxaRzl5CllYQnliMnBsWTNRdWIz\nSm5NSUdmTUEwR0NTcUdTSWIzRFFFQkFRVUFBNEdOQURDQmlRS0JnUUN5RXZjRndxWUkKUXg2O
Wpo\nSEJYekExVlpoTFgySkRVUkdROGlLbXFXUFBHaVVEWHhDcURpa1M5YnN5VFBuN2ZTaWY1Uk5HUkZF\nZwpKQmlqRitaM09RMVh5Q1JrY1kxM0VLUDJpbVVEZW0xcnB3Umg3b2gyMlBZaDU4SHFLOWsvNGdk\nZVpXVGM2QmFjCk1RckZpMlFhbWVqL
1ZpRW1KdVd2KzgyaitnN2RzV1ZNTVFJREFRQUJvNElCVnpD\nQ0FWTXdDUVlEVlIwVEJBSXcKQURBdEJnbGdoa2dCaHZoQ0FRMEVJQlllUldGemVTMVNVMEVnUjJW\ndVpYSmhkR1ZrSUVObGNuUnBabWxqWVhSbApNQjBHQTFVZERnUVdCQlFyZ09qazg
yV05zdW1wbE1T\nbXJ1d3RVeTVIVERDQjFRWURWUjBqQklITk1JSEtnQlJyClFGcjVFZ2lKV2VkWjVRWDFBaDBLVG44\nVUFLR0JwcVNCb3pDQm9ERUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlYKQkFnVEFrNURNUkF3RGdZ\nRFZRUUhFd2RTWVd4bGF
XZG9NUmN3RlFZRFZRUUtFdzVHWldSdmNtRWdVSEp2YW1WagpkREVQTUEw\nR0ExVUVDeE1HWm1Wa2JYTm5NUTh3RFFZRFZRUURFd1ptWldSdGMyY3hEekFOQmdOVkJDa1RCbVps\nClpHMXpaekVtTUNRR0NTcUdTSWIzRFFFSkFSWVhZV1J0YVc1QVptV
mtiM0poY0hKdmFtVmpkQzV2\nY21lQ0NRRGoKVUI1SFR4Y2VSVEFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQWpBTEJnTlZIUThF\nQkFNQ0I0QXdEUVlKS29aSQpodmNOQVFFRkJRQURnWUVBSjhUVGdMMHJhZ3lCdlo5RlBhdis2ZE5B\nZzEza0poQ
nYrWS9xeU9rT0RadHFwOWovCkdkOHU1emQwVkFwdXlIMnFBYzg1cUcyaEVsY0ZqUytx\nOU95YmtkQnlwQzF5cklzRSt2akZTRHZqalQxMjV6d3EKS2FNV1UwSVgyTnp2d2l4cWxYN1pxc2cz\nMHIwNzgvUHNPTGRLTlo5VWR0QXJGUHZ2b3hQRHpsTTM
4aUE9Ci0tLS0tRU5EIENFUlRJRklDQVRF\nLS0tLS0K\n',
 u'i': 1,
 u'msg': {u'commit': {u'agent': u'git',
                      u'branch': u'refs/heads/bleach',
                      u'email': u'pingou@pingoured.fr',
                      u'message': u'Use the default attributes for bleach and then add our own',
                      u'name': u'Pierre-Yves Chibon',
                      u'path': u'/srv/git/repositories/pagure.git',
                      u'repo': {u'date_created': u'1431549490',
                                u'description': u'A git centered forge',
                                u'id': 10,
                                u'name': u'pagure',
                                u'parent': None,
                                u'settings': {u'Minimum_score_to_merge_pull-request': -1,
                                              u'Only_assignee_can_merge_pull-request': False,
                                              u'Web-hooks': None,
                                              u'issue_tracker': True,
                                              u'project_documentation': True,
                                              u'pull_requests': True},
                                u'user': {u'fullname': u'Pierre-YvesChibon',
                                          u'name': u'pingou'}},
                      u'rev': u'131e07ed2538839d509880a011cd7d55c0967171',
                      u'seen': False,
                      u'stats': {u'files': {u'pagure/ui/filters.py': {u'additions': 4,
                                                                      u'deletions': 4,
                                                                      u'lines': 8}},
                                 u'total': {u'additions': 4,
                                            u'deletions': 4,
                                            u'files': 1,
                                            u'lines': 8}},
                      u'summary': u'Use the default attributes for bleach and then add our own',
                      u'username': None}},
 u'msg_id': u'2015-c6561fe2-3815-469c-a288-8f36cf8fdda3',
 u'signature': u'ZZkpicAlMkNI7EomcOI2upX32ciphowPRtpoggEysc36oyCMBWazsfOIjWJ0Z0pADtzGM+Cjy+OX\nHXMSoPO2Xp20D38ZPrT1aONzfcYiCVdWKncmyKcnUim5WqJU1k9SUrPAzPZKXG38mBMW3c7i0fpN\naTYNBhZeOv/of0n8p
l0=\n',
 u'source_name': u'datanommer',
 u'source_version': u'0.6.5',
 u'timestamp': 1434213042.0,
 u'topic': u'io.pagure.prod.pagure.git.receive'}
```

**Comment by ralphbean** [comment]
Confirmed fixed by #276.
