### ISSUE TITLE
tagger processor is handling some meetbot messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#286]
I got this from the datagrepper logs.  It appears to only happen sometimes.  This is odd.  Here's the traceback::

```python
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/lib/python2.7/site-packages/datagrepper/app.py", line 353, in raw
     message = message_card(msg, size)
   File "/usr/lib/python2.7/site-packages/datagrepper/util.py", line 119, in message_card
     subtitle = fedmsg.meta.msg2subtitle(msg, legacy=False, **config)
   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 133, in __wrapper
     return f(msg, **config)
   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 152, in __wrapper
     return f(msg, processor=processor, **config)
   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 222, in msg2subtitle
     return processor.subtitle(msg, **config)
   File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/tagger.py", line 109, in subtitle
     raise NotImplementedError("%r" % msg)
 NotImplementedError: ...
```

Caused by this message:
```python
{
    u'source_name': u'datanommer',
    u'i': 568,
    u'timestamp': 1431971250.0,
    u'msg_id': u'2015-02367ef6-0a9c-488f-adbe-87a4d79e5089',
    u'topic': u'org.fedoraproject.prod.meetbot.meeting.item.link',
    u'source_version': u'0.6.5',
    u'msg': {
        u'meeting_topic': u'F22-blocker-review',
        u'attendees': {
            u'sgallagh': 2,
            u'nirik': 34,
            u'oddshocks': 4,
            u'zodbot': 5,
            u'gbcox': 2,
            u'roshi': 187,
            u'kparal': 121,
            u'satellit': 1,
            u'kalev': 62,
            u'mclasen__': 4,
            u'danofsatx': 38,
            u'mkolman': 3,
            u'jreznik': 20,
            u'pschindl': 17,
            u'satellit_e': 6,
            u'jreznik_pp': 4,
            u'dgilmore': 30
        },
        u'chairs': {
            u'kalev': True,
            u'danofsatx': True,
            u'roshi': True,
            u'kparal': True,
            u'pschindl': True,
        },
        u'topic': u'(1221726) Fedora-repos needs updating for f22 final',
        u'url': u'http://meetbot.fedoraproject.org/fedora-blocker-review/2015-05-18/f22-blocker-review.2015-05-18-16.00',
        u'details': {
            u'linenum': 540,
            u'line': u'https://bugzilla.redhat.com/show_bug.cgi?id=1221726',
            u'time_': 1431971250.0,
            u'nick': u'roshi'
        },
        u'owner': u'roshi',
        u'channel': u'#fedora-blocker-review',
    },
}
```

**Comment by Ghost-script** [comment]
@ralphbean , Not sure what caused this error, couldn't reproduce it. For test i added this as a test in tagger.py and it generated `expected_subti` as `roshi linked to more information in the "F22-blocker-review" meeting in #fedora-blocker-review: "https://bugzilla.redhat.com/show_bug.cgi?id=1221726"`

**Comment by ralphbean** [comment]
Agreed @Ghost-script.  Thanks for looking into it!
