### ISSUE TITLE
CentOS pipeline messages sent with `null` namespace

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/fedmsg_meta_fedora_infrastructure#495]
e.g. https://apps.fedoraproject.org/datagrepper/id?id=2019-6aa280a3-05bf-48a1-affd-2e28ddf3e028&is_raw=true&size=extra-large

Note that fedmsg-meta will need to be fixed to be able to process these mesages, since we'll have these in datanommer forever.
The bug is in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/centos_ci.py#L241

The full traceback is:
````
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]: [2019-03-18 12:52:05][fmn.formatters   ERROR] An unexpected error occurred while processing an IRC batch
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]: Traceback (most recent call last):
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fmn/formatters.py", line 185, in irc_batch
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     conglomerated = fedmsg.meta.conglomerate(messages, **config.app_conf)
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 207, in conglomerate
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     [message], subject=subject, lexers=lexers, **config)
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fedmsg/meta/base.py", line 328, in produce_template
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     }) for msg in constituents])
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 152, in __wrapper
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     return f(msg, **config)
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 171, in __wrapper
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     return f(msg, processor=processor, **config)
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 347, in msg2objects
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     return processor.objects(msg, **config)
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:   File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/centos_ci.py", line 221, in objects
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]:     return set(['/'.join([namespace, pkg, commit, branch] + actions)])
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]: TypeError: sequence item 0: expected string, NoneType found
Mar 18 12:52:05 notifs-backend01.phx2.fedoraproject.org celery[13462]: [2019-03-18 12:52:05][fmn.formatters   ERROR] 2019-6aa280a3-05bf-48a1-affd-2e28ddf3e028 was among the batch that could not be processed
````

The missing namespace value is filed at https://pagure.io/fedora-ci/general/issue/42, but fedmsg-meta will need updating to deal with these messages.

**Comment by AdamWill** [comment]
Some others have null namespace too (`allpackages-build.package.queued` for e.g.) I'm working on this, along with making it handle all sorts of messages it currently doesn't handle at all.

**Comment by jimbair** [comment]
I believe this was fixed in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/496 (per the PR's notes) and this can be closed?

**Comment by AdamWill** [comment]
I believe so, but I can't close it. @smooge @nirik can either of you?
